require:
  - rubocop-rails
  - rubocop-rspec

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'db/**'
    - 'db/migrate/2019*'
    - 'db/migrate/2021*'
    - 'db/migrate/20220*'
    - 'db/migrate/202210*'
    - 'db/migrate/202211*'
    - 'spec/features/clearance/**'
