require:
  - rubocop-rails
  - rubocop-rspec

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'db/**'
