# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

bet_sizes = BetSize.create([
  { bet_size: 1, description: 'limp', color: 'red' },
  { bet_size: 2, description: '2b',   color: 'orange' },
  { bet_size: 3, description: '3b',   color: 'yellow' },
  { bet_size: 4, description: '4b',   color: 'green' },
  { bet_size: 5, description: '5b',   color: 'blue' },
  { bet_size: 6, description: '6b',   color: 'purple' }
])

bet_structures = BetStructure.create([
  { name: 'No Limit',    abbreviation: 'NL' },
  { name: 'Pot Limit',   abbreviation: 'PL' },
  { name: 'Fixed Limit', abbreviation: 'FL' }
])

hands = Hand.create([
  { hand: 'AA' },
  { hand: 'KK' },
  { hand: 'QQ' },
  { hand: 'JJ' },
  { hand: 'TT' },
  { hand: '99' },
  { hand: '88' },
  { hand: '77' },
  { hand: '66' },
  { hand: '55' },
  { hand: '44' },
  { hand: '33' },
  { hand: '22' },
  { hand: 'AKs' },
  { hand: 'AQs' },
  { hand: 'AJs' },
  { hand: 'ATs' },
  { hand: 'A9s' },
  { hand: 'A8s' },
  { hand: 'A7s' },
  { hand: 'A6s' },
  { hand: 'A5s' },
  { hand: 'A4s' },
  { hand: 'A3s' },
  { hand: 'A2s' },
  { hand: 'KQs' },
  { hand: 'KJs' },
  { hand: 'KTs' },
  { hand: 'K9s' },
  { hand: 'K8s' },
  { hand: 'K7s' },
  { hand: 'K6s' },
  { hand: 'K5s' },
  { hand: 'K4s' },
  { hand: 'K3s' },
  { hand: 'K2s' },
  { hand: 'QJs' },
  { hand: 'QTs' },
  { hand: 'Q9s' },
  { hand: 'Q8s' },
  { hand: 'Q7s' },
  { hand: 'Q6s' },
  { hand: 'Q5s' },
  { hand: 'Q4s' },
  { hand: 'Q3s' },
  { hand: 'Q2s' },
  { hand: 'JTs' },
  { hand: 'J9s' },
  { hand: 'J8s' },
  { hand: 'J7s' },
  { hand: 'J6s' },
  { hand: 'J5s' },
  { hand: 'J4s' },
  { hand: 'J3s' },
  { hand: 'J2s' },
  { hand: 'T9s' },
  { hand: 'T8s' },
  { hand: 'T7s' },
  { hand: 'T6s' },
  { hand: 'T5s' },
  { hand: 'T4s' },
  { hand: 'T3s' },
  { hand: 'T2s' },
  { hand: '98s' },
  { hand: '97s' },
  { hand: '96s' },
  { hand: '95s' },
  { hand: '94s' },
  { hand: '93s' },
  { hand: '92s' },
  { hand: '87s' },
  { hand: '86s' },
  { hand: '85s' },
  { hand: '84s' },
  { hand: '83s' },
  { hand: '82s' },
  { hand: '76s' },
  { hand: '75s' },
  { hand: '74s' },
  { hand: '73s' },
  { hand: '72s' },
  { hand: '65s' },
  { hand: '64s' },
  { hand: '63s' },
  { hand: '62s' },
  { hand: '54s' },
  { hand: '53s' },
  { hand: '52s' },
  { hand: '43s' },
  { hand: '42s' },
  { hand: '32s' },
  { hand: 'AKo' },
  { hand: 'AQo' },
  { hand: 'AJo' },
  { hand: 'ATo' },
  { hand: 'A9o' },
  { hand: 'A8o' },
  { hand: 'A7o' },
  { hand: 'A6o' },
  { hand: 'A5o' },
  { hand: 'A4o' },
  { hand: 'A3o' },
  { hand: 'A2o' },
  { hand: 'KQo' },
  { hand: 'KJo' },
  { hand: 'KTo' },
  { hand: 'K9o' },
  { hand: 'K8o' },
  { hand: 'K7o' },
  { hand: 'K6o' },
  { hand: 'K5o' },
  { hand: 'K4o' },
  { hand: 'K3o' },
  { hand: 'K2o' },
  { hand: 'QJo' },
  { hand: 'QTo' },
  { hand: 'Q9o' },
  { hand: 'Q8o' },
  { hand: 'Q7o' },
  { hand: 'Q6o' },
  { hand: 'Q5o' },
  { hand: 'Q4o' },
  { hand: 'Q3o' },
  { hand: 'Q2o' },
  { hand: 'JTo' },
  { hand: 'J9o' },
  { hand: 'J8o' },
  { hand: 'J7o' },
  { hand: 'J6o' },
  { hand: 'J5o' },
  { hand: 'J4o' },
  { hand: 'J3o' },
  { hand: 'J2o' },
  { hand: 'T9o' },
  { hand: 'T8o' },
  { hand: 'T7o' },
  { hand: 'T6o' },
  { hand: 'T5o' },
  { hand: 'T4o' },
  { hand: 'T3o' },
  { hand: 'T2o' },
  { hand: '98o' },
  { hand: '97o' },
  { hand: '96o' },
  { hand: '95o' },
  { hand: '94o' },
  { hand: '93o' },
  { hand: '92o' },
  { hand: '87o' },
  { hand: '86o' },
  { hand: '85o' },
  { hand: '84o' },
  { hand: '83o' },
  { hand: '82o' },
  { hand: '76o' },
  { hand: '75o' },
  { hand: '74o' },
  { hand: '73o' },
  { hand: '72o' },
  { hand: '65o' },
  { hand: '64o' },
  { hand: '63o' },
  { hand: '62o' },
  { hand: '54o' },
  { hand: '53o' },
  { hand: '52o' },
  { hand: '43o' },
  { hand: '42o' },
  { hand: '32o' }
])

poker_variants = PokerVariant.create([
  { name: 'Texas Holdem',           abbreviation: 'HE' },
  { name: 'Omaha',                  abbreviation: 'O' },
  { name: 'BigO',                   abbreviation: 'BigO' },
  { name: 'Mix',                    abbreviation: 'Mix' },
  { name: 'Omaha Hi-Lo',            abbreviation: 'O8' },
  { name: 'Double Board Bomb Pots', abbreviation: 'DBomb' }
])

positions = Position.create([
  { position: 'SB',       color: '#c10001' },
  { position: 'BB',       color: '#ff8f00' },
  { position: 'UTG',      color: '#edff5b' },
  { position: 'UTG1',     color: '#52e000' },
  { position: 'UTG2',     color: 'black' },
  { position: 'MP',       color: '#1a9391' },
  { position: 'LJ',       color: '#00c4da' },
  { position: 'HJ',       color: '#610c8c' },
  { position: 'CO',       color: '#d223fe' },
  { position: 'BU',       color: '#b30347' },
  { position: 'STRADDLE', color: 'black' },
])

table_sizes = TableSize.create([
  { table_size: 9, description: '10/9/8 handed' },
  { table_size: 7, description: '7 handed' },
  { table_size: 6, description: '6 handed' },
  { table_size: 5, description: '5 handed' },
  { table_size: 4, description: '4 handed' },
  { table_size: 3, description: '3 handed' },
  { table_size: 2, description: 'Heads Up' }
])
